interface OptionsSelectColumns {
  id: boolean;
  anexosFisicos: boolean;
  aplicacion: boolean;
  borrador: boolean;
  ciudad: boolean;
  codigoDependenciaOrigen: boolean;
  codigoProceso: boolean;
  codigoTramite: boolean;
  consecutivo: boolean;
  correoElectronico: boolean;
  digitalizacion: boolean;
  digitalizador: boolean;
  direccion: boolean;
  entradaOSalida: boolean;
  estado: boolean;
  expediente: boolean;
  fechaEstadoFinancieros: boolean;
  fechaRadicacionPostal: boolean;
  fechaVence: boolean;
  folios: boolean;
  funcionarioAsignado: boolean;
  funcionarioOrigen: boolean;
  horaRadicacion: boolean;
  identificacionDependenciaAsignada: boolean;
  identificacionDestinatario: boolean;
  identificacionRemitente: boolean;
  identificacionSociedad: boolean;
  linea: boolean;
  lote: boolean;
  medioEnvio: boolean;
  modulo: boolean;
  multa: boolean;
  nombreDependenciaAsignada: boolean;
  nombreDependenciaOrigen: boolean;
  nombreDestinatario: boolean;
  nombreProceso: boolean;
  nombreRemitente: boolean;
  nombreSociedad: boolean;
  nombreTramite: boolean;
  numeroRadicado: boolean;
  numeroRadicadoAnterior: boolean;
  paquete: boolean;
  postalEstado: boolean;
  referenciaExternaNumero: boolean;
  representanteLegal: boolean;
  responsableFirma: boolean;
  telefono: boolean;
  termino: boolean;
  tipoCuaderno: boolean;
  tipoSeguridad: boolean;
  usuarioQueProyecto: boolean;
  usuarioRadicador: boolean;
  detalle: boolean;
  visualizar: boolean;
  previsualizar: boolean;
}

const defaultValueOptionsSelectColumns: OptionsSelectColumns = {
  id: false,
  anexosFisicos: false,
  aplicacion: false,
  borrador: false,
  ciudad: false,
  codigoDependenciaOrigen: false,
  codigoProceso: false,
  codigoTramite: false,
  consecutivo: false,
  correoElectronico: false,
  digitalizacion: false,
  digitalizador: false,
  direccion: false,
  entradaOSalida: false,
  estado: false,
  expediente: false,
  fechaEstadoFinancieros: false,
  fechaRadicacionPostal: false,
  fechaVence: false,
  folios: false,
  funcionarioAsignado: false,
  funcionarioOrigen: false,
  horaRadicacion: false,
  identificacionDependenciaAsignada: false,
  identificacionDestinatario: false,
  identificacionRemitente: false,
  identificacionSociedad: false,
  linea: false,
  lote: false,
  medioEnvio: false,
  modulo: false,
  multa: false,
  nombreDependenciaAsignada: false,
  nombreDependenciaOrigen: false,
  nombreDestinatario: false,
  nombreProceso: false,
  nombreRemitente: false,
  nombreSociedad: false,
  nombreTramite: false,
  numeroRadicado: false,
  numeroRadicadoAnterior: false,
  paquete: false,
  postalEstado: false,
  referenciaExternaNumero: false,
  representanteLegal: false,
  responsableFirma: false,
  telefono: false,
  termino: false,
  tipoCuaderno: false,
  tipoSeguridad: false,
  usuarioQueProyecto: false,
  usuarioRadicador: false,
  detalle: false,
  visualizar: false,
  previsualizar: false,
};

export { OptionsSelectColumns, defaultValueOptionsSelectColumns };
