interface OptionsBasicaSelectColumns {
  id: boolean;
  anexosFisicos: boolean;
  codigoDependenciaOrigen: boolean;
  borrador: boolean;
  codigoTramite: boolean;
  consecutivo: boolean;
  correoElectronico: boolean;
  direccion: boolean;
  ciudad: boolean;
  entradaOSalida: boolean;
  estado: boolean;
  expediente: boolean;
  fechaRadicacionPostal: boolean;
  folios: boolean;
  funcionarioAsignado: boolean;
  funcionarioOrigen: boolean;
  horaRadicacion: boolean;
  identificacionDependenciaAsignada: boolean;
  identificacionDestinatario: boolean;
  identificacionRemitente: boolean;
  identificacionSociedad: boolean;
  linea: boolean;
  nombreDependenciaAsignada: boolean;
  nombreDependenciaOrigen: boolean;
  nombreDestinatario: boolean;
  nombreRemitente: boolean;
  nombreSociedad: boolean;
  nombreTramite: boolean;
  numeroRadicado: boolean;
  numeroRadicadoAnterior: boolean; 
  tipoSeguridad: boolean;
  telefono: boolean;
  termino: boolean;
  usuarioRadicador: boolean;
  detalle: boolean;
  visualizar: boolean;
  previsualizar: boolean;
}

const basicaValueOptionsSelectColumns: OptionsBasicaSelectColumns = {
  id: false,
  anexosFisicos: false,
  codigoDependenciaOrigen: false,
  borrador: false,
  codigoTramite: false,
  consecutivo: false,
  correoElectronico: false,
  direccion: false,
  ciudad: false,
  entradaOSalida: false,
  estado: false,
  expediente: false,
  fechaRadicacionPostal: false,
  folios: false,
  funcionarioAsignado: false,
  funcionarioOrigen: false,
  horaRadicacion: false,
  identificacionDependenciaAsignada: false,
  identificacionDestinatario: false,
  identificacionRemitente: false,
  identificacionSociedad: false,
  linea: false,
  nombreDependenciaAsignada: false,
  nombreDependenciaOrigen: false,
  nombreDestinatario: false,
  nombreRemitente: false,
  nombreSociedad: false,
  nombreTramite: false,
  numeroRadicado: false,
  numeroRadicadoAnterior: false, 
  tipoSeguridad: false,
  telefono: false,
  termino: false,
  usuarioRadicador: false,
  detalle: false,
  visualizar: false,
  previsualizar: false,
};

export { OptionsBasicaSelectColumns, basicaValueOptionsSelectColumns };
